# Build Lifecycle
# before_install -> install -> before_script -> script
# -> after_success or after_failure -> after_script

language: android
sudo: false
jdk: oraclejdk7
android:
  components:
    - platform-tools
    - tools
    - android-22
    - build-tools-22.0.1
    - extra-android-support
    - extra-android-m2repository
before_script:
  - chmod +x gradlew
