language: android

sudo: false

jdk: oraclejdk7

android:
  components:
    - android-22
    - build-tools-22.0.1

before_script:
 - echo "chmod +x gradlew before_script"
 - chmod +x gradlew

before_install:
 - echo "chmod +x gradlew before_install"
 - chmod +x gradlew
