# Build Lifecycle
# before_install -> install -> before_script -> script
# -> after_success or after_failure -> after_script

language: android
sudo: false
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-23
      ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.0
    - extra-android-support
    - extra-android-m2repository
    #- sys-img-armeabi-v7a-android-23

before_script:
  # Make gradlew have permission to execute
  - chmod +x gradlew
  # Create, start and wait device
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  #- emulator -avd test -no-skin -no-audio -no-window &
  #- android-wait-for-emulator
  #- adb shell input keyevent 82 &

script:
  # Default is "./gradlew build connectedCheck"
  - ./gradlew --full-stacktrace build
